export const translations = {
    en: {
        translation: {
            'fullName': 'Bagryancev Maxim, 35',
            'directions': 'Hardworking and passionate frontend developer',
            'stack': '(Node.js, Next.js, ReactJS, TypeScript)',
            'contactByTelegram': 'Contact by Telegram',
            'sendEmail': 'Send E-mail',
            'contactByPhone': 'Contact by Phone',
            'location': 'Russia, Samara region',
            'description1': 'Hardworking and passionate frontend developer. Pedantry, determination and commitment in every project are my main strengths.',
            'description2': 'I took a part in private as well as commercial projects.',
            'description3': 'I am looking forward to become a part of your team 😉',
            'experience': 'Experience (1+ years)',
            'mechanica': 'December 2021 - now',
            'mechDescription': 'Designing react components, implementation of new features, fixing bugs, reworking the old (legacy) react code into a new one that meets new standards (class → functional with hooks).',
            'rosneft': 'March 2011 - January 2022',
            'rosneftDescription': 'Development of technical specifications. Scientific and technical support for the implementation of new technologies. I am the author and co-author of scientific and technical articles:Best Practices in Thermal Petrophysics as a Tool for Reducing Uncertainties in Modeling Thermal Studies of Unconventional ReservoirsOptimization of technological solutions in the development of extra-heavy oil deposits based on the study of core and oil properties.A multi-scale method of seismic geomodeling of the development of matter and the development of compacted reservoirs according to the formula of A. Einstein, or if clay could speak.',
            'accounts': 'Accounts',
            'projects': 'Projects',
            'education': 'Education',
            'skills': 'Skills',
            'languages': 'Languages',
            'languages-russia': 'Russian:',
            'languages-english': 'English:',
            'languages-russia-des': ' Native',
            'languages-english-des': ' B1, Technical English: documentation reading, correspondence, commenting',
            'site': 'Site:',

            // pwc - project
            'pwc-title-description': 'Educational platform',
            'pwc-description': 'Educational platform working in the following areas: management, audit, analytics. Provides users with the ability to order courses online, as well as post information about their courses.',
            'pwc-involvement': 'Involvement in the project',
            'pwc-involvement-description': 'Partial. Improvement of functionality, bug fixes, rebranding.',
            'pwc-used-technologies': 'Used technologies',
            'pwc-technologies': 'React.js, SASS preprocessor.',
            'pwc-completed-tasks': 'Completed tasks',
            'pwc-tasks': 'Refinement / editing / updating of individual blocks of the site, as well as information in them. Bug fixesRebranding and website redesign. (replacing the color palette, styles, logos)',

            // surdoclass - project
            'surdoclass-title-description': 'Educational platform',
            'surdoclass-description': 'Educational platform for online learning for people with hearing impairments.',
            'surdoclass-involvement': 'Involvement in the project',
            'surdoclass-involvement-description': 'Full. Creating a project from scratch. Collaboration in a team.',
            'surdoclass-used-technologies': 'Used technologies',
            'surdoclass-technologies': 'React.js, Next.js, Redux.js-Toolkit, TypeScript, SASS preprocessor, Axios',
            'surdoclass-completed-tasks': 'Completed tasks',
            'surdoclass-tasks': 'Implementation of the functionality according to the TOR. · Participation in the development of the project architecture. Layout according to the layout with adaptation for various devices. Development of individual UI components. Development of individual application pages. Implementation of the filter block. Implementation of data exchange with the server.',

            // skillmaps - project
            'skillmaps-title-description': 'Educational platform',
            'skillmaps-description': 'Educational platform for technical specialists in the field of web application development, with the ability to track learning progress',
            'skillmaps-involvement': 'Involvement in the project',
            'skillmaps-involvement-description': 'Partial. Improvement of functionality, development of new features, bug fixes.',
            'skillmaps-used-technologies': 'Used technologies',
            'skillmaps-technologies': 'React.js, Next.js, Redux.js-Toolkit, TypeScript, SASS preprocessor, Axios. SCRUM',
            'skillmaps-completed-tasks': 'Completed tasks',
            'skillmaps-tasks': 'Adaptation of ready-made pages for various devices. Development of individual UI components according to the layout. Development of individual application pages.',

            // car-sharing - project
            'car-sharing-title-description': 'Car rental service',
            'car-sharing-description': 'Car sharing is cars that can be rented through an app for a minute, an hour or a day.',
            'car-sharing-involvement': 'Involvement in the project',
            'car-sharing-involvement-description': 'Full. Creating a project from scratch.',
            'car-sharing-used-technologies': 'Used technologies',
            'car-sharing-technologies': 'React.js, Redux.js, SASS preprocessor, Axios, Yandex.Map javascript API, antd UI library',
            'car-sharing-completed-tasks': 'Completed tasks',
            'car-sharing-tasks': 'Implementation of the functionality according to the TOR. Participation in the development of the project architecture. Layout according to the layout with adaptation for various devices. Development of UI components. Development of the client part. Development of the admin part',
            'mechanica-skills': 'Skills',

            // mechanica - project
            'mechanica-title-description': 'Corporate website',
            'mechanica-description': 'development of digital services for large and medium-sized businesses (ex-ANMEDIO)',
            'mechanica-involvement': 'Involvement in the project',
            'mechanica-involvement-description': 'Full. Creating a project from scratch.',
            'mechanica-used-technologies': 'Used technologies',
            'mechanica-technologies': 'React.js, SASS preprocessor, UI library',
            'mechanica-completed-tasks': 'Completed tasks',
            'mechanica-tasks': 'Participation in the development of the project architecture. Layout according to the layout with adaptation for various devices. Development of UI components. ',

            // education SimbirSoft
            'year': 'August 2021 - December 2021 (Course)',
            'institution': 'SimbirSoft',
            'institution_description': ' - IT-company',
            'faculty': 'Direction:',
            'faculty__description': ' Frontend-course (JavaScript, React)',

            // education SamGTU
            'year-higher': '2004 - 2009 (Higher, specialist)',
            'institution-higher': 'University',
            'institution_description-higher': ' - Samara State Technical University',
            'faculty-higher': 'Faculty:',
            'faculty__description-higher': ' Development of oil and gas fields',
        },
    },

    ru: {
        translation: {
            'fullName': 'Багрянцев Максим, 35',
            'directions': 'Трудолюбивый и увлеченный фронтенд-разработчик',
            'stack': '(Node.js, Next.js, ReactJS, TypeScript)',
            'contactByTelegram': 'Связаться по Telegram',
            'sendEmail': 'Отправить на почту',
            'contactByPhone': 'Позвонить по телефону',
            'location': 'Россия, г. Самара',
            'description1': 'Трудолюбивый и увлеченный frontend разработчик. Педантичность, целеустремленность в каждом проекте – это мои сильные стороны.',
            'description2': 'Принимал участие как в частных, так и в коммерческих проектах.',
            'description3': 'Я с нетерпением жду возможности стать частью вашей команды 😉',
            'experience': 'Опыт (1+ год)',
            'mechanica': 'Декабрь 2021 - по настоящее время',
            'mechDescription': 'Проектирование компонентов реагирования, внедрение новых функций, исправление ошибок, переработка старого (унаследованного) кода реагирования в новый, отвечающий новым стандартам (класс → функционал с хуками).',
            'rosneft': 'Март 2011 - Январь 2022',
            'rosneftDescription': 'Разработка технического задания. Научно-техническое сопровождение работ по внедрению новых технологий. Являюсь автором и сооавтором научно-технических статей: Advanced methods of thermal petrophysics as a means to reduce uncertainties during thermal eor modeling of unconventional reservoirs. Optimization of Process Solutions in Developing Extra-Heavy Oil Pools at the Basis of Core Studies and Oil Properties Investigation. Многомасштабный метод сейсмического геомоделирования развития состояния вещества и эволюции уплотненных коллекторов по формуле А. Эйнштейна, или если бы глина умела говорить.',
            'accounts': 'Аккаунты',
            'projects': 'Проекты',
            'education': 'Образование',
            'skills': 'Скиллы',
            'languages': 'Языки',
            'languages-russia': 'Русский:',
            'languages-english': 'Английский:',
            'languages-russia-des': ' Носитель',
            'languages-english-des': ' B1, Технический английский: чтение документации, переписка, комментирование',
            'site': 'Сайт:',

            // pwc - project
            'pwc-title-description': 'Образовательная платформа',
            'pwc-description': 'Образовательная платформа, работающая по направлениям: менеджмента, аудита, аналитики. Обеспечивает пользователям возможность заказывать курсы онлайн, а также размещать информацию о своих курсах.',
            'pwc-involvement': 'Вовлеченность в проект',
            'pwc-involvement-description': 'Частичная. Доработка функционала, исправление багов, ребрендинг.',
            'pwc-used-technologies': 'Используемые технологии',
            'pwc-technologies': 'React.js, SASS preprocessor.',
            'pwc-completed-tasks': 'Выполненные задачи',
            'pwc-tasks': 'Доработка/редактирование/актуализация отдельных блоков сайта, а также информация в них. Исправление багов. Ребрендинг и редизайн сайта. (замена цветовой палитры, стилей, логотипов)',

            // surdoclass - project
            'surdoclass-title-description': 'Образовательная платформа',
            'surdoclass-description': 'Образовательная платформа для онлайн обучения людей с ограниченным слуховым восприятием',
            'surdoclass-involvement': 'Вовлеченность в проект',
            'surdoclass-involvement-description': 'Полная. Создание проекта с нуля. Совместная работа в команде',
            'surdoclass-used-technologies': 'Используемые технологии',
            'surdoclass-technologies': 'React.js, Next.js, Redux.js-Toolkit, TypeScript, SASS preprocessor, Axios',
            'surdoclass-completed-tasks': 'Выполненные задачи',
            'surdoclass-tasks': 'Реализация функционала по ТЗ. Участие в разработке архитектуры проекта. Верстка по макету с адаптацией под различные устройства. Разработка отдельных UI компонентов. Разработка отдельных страниц приложения. Реализация блока фильтрации . Реализация обмена данных с сервером.',

            // skillmaps - project
            'skillmaps-title-description': 'Образовательная платформа',
            'skillmaps-description': 'Образовательная платформа для технических специалистов в области разработки web приложений, с возможностью отслеживания прогресса в обучении.',
            'skillmaps-involvement': 'Вовлеченность в проект',
            'skillmaps-involvement-description': 'Частичная. Доработка функционала, разработка новых фитч, исправление багов.',
            'skillmaps-used-technologies': 'Используемые технологии',
            'skillmaps-technologies': 'React.js, Next.js, Redux.js-Toolkit, TypeScript, SASS preprocessor, Axios. SCRUM',
            'skillmaps-completed-tasks': 'Выполненные задачи',
            'skillmaps-tasks': 'Адаптация готовых страниц под различные устройства. Разработка отдельных UI компонентов по макету. Разработка отдельных страниц приложения.',

            // car-sharing - project
            'car-sharing-title-description': 'Сервис аренды автомобилей',
            'car-sharing-description': 'Каршеринг — это такие машины, которые можно брать через приложение на минуту, час или день.',
            'car-sharing-involvement': 'Вовлеченность в проект',
            'car-sharing-involvement-description': 'Полная. Создание проекта с нуля.',
            'car-sharing-used-technologies': 'Используемые технологии',
            'car-sharing-technologies': 'React.js, Redux.js, SASS preprocessor, Axios, Yandex.Map javascript API, UI библиотека antd',
            'car-sharing-completed-tasks': 'Выполненные задачи',
            'car-sharing-tasks': 'Реализация функционала по ТЗ. Участие в разработке архитектуры проекта. Верстка по макету с адаптацией под различные устройства. Разработка UI компонентов. Разработка клентской части. Разработка админской части',

            // mechanica - project
            'mechanica-title-description': 'Корпоротивный сайт',
            'mechanica-description': 'Mechanica — разработка digital-сервисов для крупного и среднего бизнеса (ex-ANMEDIO)',
            'mechanica-involvement': 'Вовлеченность в проект',
            'mechanica-involvement-description': 'Полная. Создание проекта с нуля.',
            'mechanica-used-technologies': 'Используемые технологии',
            'mechanica-technologies': 'React.js, SASS preprocessor, UI library',
            'mechanica-completed-tasks': 'Выполненные задачи',
            'mechanica-tasks': 'Участие в разработке архитектуры проекта. Вёрстка по макету с адаптацией под различные устройства. Разработка UI-компонентов.',

            // education SimbirSoft
            'year': 'август 2021 - декабрь 2021 гг. (Курсы)',
            'institution': 'СимбирСофт',
            'institution_description': ' - IT-компания',
            'faculty': 'Направление:',
            'faculty__description': ' Frontend-практикум (JavaScript, React)',

            // education SamGTU
            'year-higher': '2004 - 2009 гг. (Высшее, специалист)',
            'institution-higher': 'ВУЗ',
            'institution_description-higher': ' - Самарский государственный технический университет',
            'faculty-higher': 'Факультет:',
            'faculty__description-higher': ' Разработка нефтяных и газовых месторождений',
        }
    }
};
